application: gae-todomvc
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /image
  static_dir: image

- url: /font
  static_dir: font
  mime_type: font/opentype

- url: /favicon.ico
  static_files: image/favicon.ico
  upload: image/favicon.ico

- url: .*
  script: main.app

libraries:
- name: PIL
  version: latest

- name: django
  version: 1.2

inbound_services:
- channel_presence